
name = "Aovi Deshpande"
subtitle = "4th year Undergraduate in Chemical Engineering"
email = "aovideshpande@gmail.com"
phone = "+91 7385707478"
website = "www.aovideshpande.com"
linkedin = "https://www.linkedin.com/in/aovi-deshpande-9b29a8185"
linkedintext = "/aovi-deshpande"
twitter = "@aovideshpande"
github = "github.com/aovi14"
location = "Mumbai, India"


## EDUCATION ######

[[Education]]
institute = "Shivajirao S. Jondhale College of Engineering"
subtext = "B.Tech, Department of Chemical Engineering"
start = 2017
end = 2021
location = "Mumbai, India"
gradetext = "CGPA"
gradevalue = "9.06"
grademax = "10"

[[Education]]
institute = "Pandit Bachraj Vyas Vidyalaya"
subtext = "Higher Secondary, Maharashtra State Board"
start = 2015
end = 2017
location = "Nagpur, India"
gradetext = "Score"
gradevalue = "76"
grademax = "100"

[[Education]]
institute = "Chanda Devi Saraf High School"
subtext = "Secondary School, Indian Certificate of Secondary Education"
start = 2004
end = 2015
location = "Nagpur, India"
gradetext = "Score"
gradevalue = "92"
grademax = "100"

## EDUCATION ######

## PROJECTS #######

[[Project]]
title = "Process Simulation for Azeotropic Systems" # Be specific
related = "Process Engineering, Cost Analysis"
guide = "Prof. John Doe"
guidelink = "https://johndoe.com"
reportlink = "https://www.github.com/aovi14/process_sim"
period = "Summer 2020"
location = "Mumbai"
locationlink = "https://www.mumbai.com"
point1 = "Created a start to end process simulation of a three component azeotropic system"
point2 = "The process had nitric acid, HCl and water system which was seperated by a dual pressure swing distillation column"
point3 = "Cost analysis along with debottelnecking and process optimization for the system was also carried out"

[[Project]]
title = "Data Analysis" # Be specific
related = "Predictive Modelling"
guide = "Prof. John Doe"
guidelink = "https://johndoe.com"
reportlink = "https://www.github.com/aovi14/process_sim"
period = "Summer 2020"
location = "Mumbai"
locationlink = "https://www.mumbai.com"
point1 = "Learned about predictive modelling and basics of machine learning"
point2 = "Applied predictive modelling and statistical methods to analyse data of an Insurance company and finding out the probability of failure of payment based on past records"
point3 = ""

[[Project]]
title = "Cost-Effective Heat Exchanger" # Be specific
related = "Process Equipment Design"
guide = "Prof. John Doe"
guidelink = "https://johndoe.com"
reportlink = "https://www.github.com/aovi14/process_sim"
period = "Autumn 2019"
location = "Mumbai"
locationlink = "https://www.mumbai.com"
point1 = "Developed a working model of variable temperature outlet shell and tube heat exchanger from scratch"
point2 = "The model was awarded 1st prize in TSEC under IICHE (Indian Institute of Chemical Engineers)"
point3 = "The project received praises for its temperature adjustability and simple scalability"

[[Project]]
title = "Steam Trap Health Monitoring." # Be specific
related = "Process Equipment Design"
guide = "Prof. John Doe"
guidelink = "https://johndoe.com"
reportlink = "https://www.github.com/aovi14/process_sim"
period = "Winter 2017"
location = "Mumbai"
locationlink = "https://www.mumbai.com"
point1 = "Developed a Steam Trap Health Monitor device which works by classifying vibration patterns."
point2 = "Lead the team of six throughout the whole development operation."
point3 = "The model reached the semi finals in Smart India Hackathon 2019 (Hardware Edition)."

# [[Project]]
# title = "Smart Bin" # Be specific
# related = "Process Engineering, Cost Analysis"
# guide = "Prof. John Doe"
# guidelink = "https://johndoe.com"
# reportlink = "https://www.github.com/aovi14/process_sim"
# period = "Spring 2018"
# location = "Mumbai"
# locationlink = "https://www.mumbai.com"
# point1 = "Implemented a SMART bin on Arduino UNO microcontroller platform."
# point2 = "Used ultrasonic sensor interfaces to give automatic functioning and moving abilities."
# point3 = "Added support for automated notifications about bin status through use of a GSM module."


## PROJECTS #######

## INTERNSHIP #####

[[Internship]]
title = "Adya Group" # Mention content
guide = "Mr. Indraneel Chatterji"
guidelink = "https://www.linkedin.com/in/indraneelchatterjee/"
period = "Summer 2020"
location = "Adya, Mumbai"
locationlink = "https://adhya.com"
point1 = "Process Simulation Intern"
point2 = "Learned comprehensively about DWSIM and performed simulation on unit operations and process"
point3 = "Generated a report on software uses and limitations along with one practical project"

[[Internship]]
title = "Rashtriya Chemical Factory" # Mention content
guide = "Mr. Vivek Newalkar"
guidelink = "https://www.linkedin.com/in/vivek-newalkar-b68aab85/"
period = "Winter 2019"
location = "RCF, Alibagh"
locationlink = "https://www.rcfltd.com/"
point1 = "Vocational trainee at ammonia plant"
point2 = "Overview of urea, argon, heavy water, carbonmonoxide, steam generation plants"
point3 = "Got familiarized with Digital Control Systems and their effects on pneumatic valves"

[[Internship]]
title = "Vijay Gas Industries" # Mention content
guide = "Mr. Deepak Sawant"
guidelink = "https://www.linkedin.com"
period = "Winter 2019"
location = "VGI, Ambernath"
locationlink = "http://www.vgiammonia.com/"
point1 = "Worked as an intern in Ammonia and Nitric Acid manufacturing plant"
point2 = "Performed detailed analysis on various unit operations and their practical applications"
point3 = "Generated a comprehensive report on the working of the plan"


## INTERNSHIP #####

## ACHIEVEMENT ####

[[Achievement]]
point = "Qualified for Eyantra 2018 stage 2 held by CSE department of IITB among 200 participating colleges" # Not more than length of this point
year = "2019"

[[Achievement]]
point = "Ranked 1st in stage 1 of Chemophilia organized by Azeotropy, IIT Bombay"
year = "2019"

[[Achievement]]
point = "Presented a poster on treatment of “Recycling of non-recyclable plastics” at Thadomal sahani college for Techfest held under IICHE (Indian Institute of Chemical Engineers)"
year = "2019"

[[Achievement]]
# point = "Presented a review paper on design of horizontal distillation column at ICT Mumbai for OYCE Competition. "
point = "Presented a review paper on design of horizontal distillation column at ICT Mumbai" 
year = "2019"

[[Achievement]]
point = "Attended an industry-academy programme at DAE Convention, Bhabha Atomic Research Centre."
year = "2018"

[[Achievement]]
point = "Awarded 1st prize for poster presentation on Science day."
year = "2018"

[[Achievement]]
point = "Led a team of 4 for Indian Innovation Challenge Design Contest in developing a SMART Helmet."
year = "2018"

[[Achievement]]
point = "Participated in essay, quiz and debate competition held by office of Deputy Commissioner"
year = "2017"




## ACHIEVEMENT ####

## POR ############

[[POR]]
position = "Department Co. Technical Head"
period = "Sept 2019 - Jan 2020"
location = "Mumbai"
point1 = "Managed social media strategy, branding and street teams to ensure event attendance"
point2 = "Conducted a three level technical quiz and held a debate competition"
point3 = "Prepared event reports and guided event managers"

[[POR]]
position = "Ambassador Relation Officer"
period = "Sept 2020 - Present"
location = "Mumbai"
point1 = "Helping out with the Student Outreach Program of Chemtech Foundation (India's leading Industry association)"
point2 = "Coordinating with the campus ambassador for annual series of international exhibitions and conferences"
point3 = "Motivating students for maximum participation and keeping the record of the same"

[[POR]]
position = "Student Mentor"
period = "Sept 2019 - Present"
location = "Mumbai"
point1 = "Served as a peer mentor for 8 students in guiding their academics and college life"
point2 = "Counseled students individually and in group sessions to build personal and academic motivation"
point3 = "Guided them in their research-oriented work"

[[POR]]
position = "Magazine Editor"
period = "May 2020 - Aug 2020"
location = "Mumbai"
point1 = "Worked on the annual Chemical Department magazine at college level"
point2 = "Did extensive research on content along with graphic editing for magazine"
point3 = "Coordinating with the faculty and preparing the content accordingly"

## POR ############


## Area of Interest ##

[[Interest]]
text = "Stock exchange"

[[Interest]]
text = "Historic architectutre and Mythology"

[[Interest]]
text = "Quantum Mechanics"

[[Interest]]
text = "Studying Graphs and charts"

## Area of Interest ##

## SKILLS #########

[[Technical]]
text = "MS-Excel"

[[Technical]]
text = "AutoCAD"

[[Technical]]
text = "Scilib"

[[Technical]]
text = "Python"

[[Technical]]
text = "DWSIM"

[[Technical]]
text = "Basic Aspen Hysys"


###

[[Soft]]
text = "Leadership"

[[Soft]]
text = "Communication"

[[Soft]]
text = "Decision Making"

[[Soft]]
text = "Social Skills"

[[Soft]]
text = "Time Management"

###

[[Hobbies]]
text = "Playing Piano"

[[Hobbies]]
text = "Listening Music"

[[Hobbies]]
text = "Online Surfing"

[[Hobbies]]
text = "Shopping"

[[Hobbies]]
text = "Trekking"

[[Hobbies]]
text = "Reading Books"

###

[[Talents]]
text = "Stand-up Comedy"

[[Talents]]
text = "Negotiation"

[[Talents]]
text = "Event Anchoring"


## SKILLS #########

[[Interests]]
text = "Sitting"

[[Interests]]
text = "Shopping"

## Certificates ####

[[Certificates]]
text =  "NPTEL course on Natural Gas Engineering "
rating = "67.9%"
year = "2019"
location = "IIT Guhuwati"

[[Certificates]]
text =  "Course on Health and Chemicals"
rating = "91%"
year = "2020"
location = "John Hopkins University"

[[Certificates]]
text =  "Course on Data analysis"
rating = ""
year = "2020"
location = "Internshala"

[[Certificates]]
text =  "Webinar on Zero Liquid Waste Discharge"
rating = ""
year = "2020"
location = "Bhartiya Vidhyapeeth"

[[Certificates]]
text =  "Quiz on Industrial Safety"
rating = ""
year = "2020"
location = "Tatya Saheb Kore Institute of Engineering and Technology"


# [[Certificates]]
# text =  "Webinar on  Design of shell and tube heat exchanger."
# rating = ""
# year = "2020"
# location = "Empress Mall"


## Extracurricular ###

[[Extracurricular]]
text = "Underwent one year long training in Hockey under National Sports Organization"
year = "2017"

[[Extracurricular]]
text = "Underwent one year long training in Hockey under National Sports Organization"
year = "2017"

[[Extracurricular]]
text = "Underwent one year long training in Hockey under National Sports Organization"
year = "2017"

[[Extracurricular]]
text = "Underwent one year long training in Hockey under National Sports Organization"
year = "2017"

[[Extracurricular]]
text = "Underwent one year long training in Hockey under National Sports Organization"
year = "2017"

## Extracurricular ###
